[package]
name = "harelsp"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
lsp-server = "0.7.7"
lsp-types = "0.97.0"
serde_json = "1.0.132"
smallvec = "1.13.2"
smol_str = "0.3.2"
